AWSTemplateFormatVersion: "2010-09-09"
Resources:
  EC2EventRule:
    Type: "AWS::Events::Rule"
    Properties:
      Name: "EC2StartStopInstancesRule"
      EventPattern:
        Source:
          - "aws.ec2"
        DetailType:
          - "AWS API Call via CloudTrail"
        Detail:
          eventSource:
            - "ec2.amazonaws.com"
          eventName:
            - "StartInstances"
            - "StopInstances"
      State: "ENABLED"
      Targets:
        - Arn: !ImportValue MyLambdaFunctionArn
          Id: "TargetFunc1"
          Input: "{}"