AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function using an existing IAM role and importing log group name

Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: my-lambda-function
      Handler: index.handler
      Role: !ImportValue LambdaExecutionRoleArn
      Runtime: python3.9
      Timeout: 10
      Code:
        S3Bucket: snooze-cf-bucket
        S3Key: projects/get-awslogs/LambdaCode/LambdaCode.zip
      Environment:
        Variables:
          OUTPUT_LOG_GROUP: !ImportValue DestinationLogGroup  # 他スタックでエクスポートされたロググループ名

  # CloudWatchサービスがLambda関数に対しての実行権限を付与する設定
  MyLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt MyLambdaFunction.Arn
      Principal: logs.ap-northeast-1.amazonaws.com
      SourceArn: arn:aws:logs:ap-northeast-1:190805427049:log-group:sender-log-group:*

Outputs:
  LambdaFunctionName:
    Value: !Ref MyLambdaFunction

  LambdaFunctionArn:
    Description: "Lambda function ARN"
    Value: !GetAtt MyLambdaFunction.Arn
    Export:
      Name: MyLambdaFunctionArn

