Resources:
  MyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: sender-log-group
      RetentionInDays: 7

Outputs:
  MyLogGroupArn:
    Value: !GetAtt MyLogGroup.Arn
    Export:
      Name: SenderLogGroupArn
  
  MyLogGroupName:
    Description: LogGroup
    Value: !Ref MyLogGroup
    Export:
      Name: SenderLogGroupName
