Resources:
  LogSubscription:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      LogGroupName: !ImportValue SenderLogGroupName
      FilterPattern: "?Error"
      DestinationArn: !ImportValue MyLambdaFunctionArn
